server:
  port: 8080

info:
  instance: ${INSTANCE_NAME:backend-b-default}

spring:
  application:
    name: backend-b
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
