global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'myservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['myservice:8080']

  - job_name: 'backend-a'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-a-1:8080']

  - job_name: 'backend-b'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-b-1:8080']

  - job_name: 'docker-stats'
    static_configs:
      - targets: ['docker-stats-exporter:9487']

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=test_results"
