spring:
  config:
    activate:
      on-profile: loadbalancer

  application:
    name: myservice

  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
