spring:
  config:
    activate:
      on-profile: retry

server:
  port: 8080
  address: 0.0.0.0

resilience4j.retry:
  instances:
    backendA:
      maxAttempts: 3
      waitDuration: 1s
    backendB:
      maxAttempts: 3
      waitDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

backend:
  a:
    url: http://backend-a-1:8080/data
    unstableUrl: http://backend-a-1:8080/unstable
  b:
    url: http://backend-b-1:8080/data
