spring:
  config:
    activate:
      on-profile: default

server:
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

backend:
  a:
    url: http://backend-a-1:8080/data
    unstableUrl: http://backend-a-1:8080/unstable
  b:
    url: http://backend-b-1:8080/data
