spring:
  config:
    activate:
      on-profile: circuitbreaker
server:
  port: 8080
  address: 0.0.0.0

resilience4j:
  circuitbreaker:
    instances:
      backendA:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true 
      backendB:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        slidingWindowType: COUNT_BASED

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:  
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

backend:
  a:
    url: http://backend-a-1:8080/data
    unstableUrl: http://backend-a-1:8080/unstable
  b:
    url: http://backend-b-1:8080/data