spring:
  config:
    activate:
      on-profile: retry

server:
  port: 8080
  address: 0.0.0.0

resilience4j:
  retry:
    instances:
      backendA:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2.0
        randomized-wait: true
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
        fail-after-max-attempts: true

      backendB:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2.0
        randomized-wait: true
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
        fail-after-max-attempts: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

backend:
  a:
    url: http://backend-a-1:8080/data
    unstableUrl: http://backend-a-1:8080/unstable
  b:
    url: http://backend-b-1:8080/data
